#!/bin/bash
set -e

export RUNTIME_C=$PWD/../src/runtime/runtime.c
export DECAF_BIN=$PWD/../decaf

parse_args() {
    case $1 in
        1) export DIR=PA1 ; export TGT=PA1 ;;
        2) export DIR=PA2 ; export TGT=PA2 ;;
        3) export DIR=PA3 ; export TGT=PA3 ;;
        *) echo "Usage: $0 [1|2|3]" ; exit 1 ;;
    esac
    [[ -f $DECAF_BIN ]] || (echo "Cannot find $DECAF_BIN. Did you 'make'?" ; exit 1)
}

prepare() {
    cd input && TESTS=(`ls -1 *.decaf | sed 's/\.decaf//'`) && cd ..
    rm -rf output && mkdir output
}

run_test() {
    T=$1
    LL_FILENAME=$T.ll

    if [[ $TGT = PA3 ]];then
        $DECAF_BIN -t $TGT -d output input/$T.decaf >output/$LL_FILENAME 2>&1
        clang-12 $RUNTIME_C output/$LL_FILENAME -o output/$T && output/$T > output/$T.output 2>&1 || true
    else
        $DECAF_BIN -t $TGT -d output input/$T.decaf >output/$T.output 2>&1 || true
    fi
}
export -f run_test

check_output(){ 
    NPASS=0
    NTOT=${#TESTS[@]}

    RED='\033[0;31m'
    GREEN='\033[0;32m'
    NC='\033[0m'
    COLOR=$RED

    for T in ${TESTS[@]}; do
        echo "==========" $T
        diff -qZ output/$T.output expected/$T.result && NPASS=$((NPASS+1))
    done
    if [ ${NPASS} == ${NTOT} ];then
        COLOR=${GREEN}	
    fi

    echo -e "${COLOR}Pass/Total: ${NPASS}/${NTOT}${NC}"
    exit `[ $NPASS = $NTOT ]`
}


parse_args $1
cd $DIR
prepare
parallel --halt now,fail=1 run_test ::: ${TESTS[@]}
check_output
